name: devops-2026-demo

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_DIRECTORY: ${{ vars.TF_DIRECTORY }}

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/demo.yml"
      - "**.tf"
      - "**.tfvars"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: TF code checkout
        uses: actions/checkout@v4

      - name: Upload configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ vars.TF_WORKSPACE }}
          directory: ${{ vars.TF_DIRECTORY }}
          speculative: false

      - name: Create HCP Terraform plan-only run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          workspace: ${{ vars.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: true
